title:             multicus
email:             
description:       My Blog about Tech... 'n Stuff
author:            multicus
baseurl:           ""
url:               "https://multicus.github.io"

# Social Profiles
twitter_username:
github_username:   multicus
facebook_username:

# Build settings
markdown:          kramdown
paginate:          40
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  
# Front matter defaults
defaults:
  -
    scope:
      path: "_posts"
    values:
        layout: "post"
        permalink: "/posts/:title/"

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: multicus